"""add photo_key to about

Revision ID: 200f5e22c9b4
Revises: a41d734e4566
Create Date: 2026-06-19 21:12:55.251430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '200f5e22c9b4'
down_revision: Union[str, None] = 'a41d734e4566'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('about', sa.Column('photo_key', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('about', 'photo_key')
    # ### end Alembic commands ###
